name: LINT

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, intl, gd

      - name: Install dependencies
        run: composer install --dev

      - name: Run lint code
        run: composer lint
